forum_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import ForumListView, ThreadListView, profile_view, RegisterView, PostListView, PostDetailView, \
    CommentDeleteView, CreatePostView, GetThreadsForForumView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'forum_app'

urlpatterns = [
    path('forums/', ForumListView.as_view(), name='forum_list'),
    path('forums/<slug:forum_slug>/threads/', ThreadListView.as_view(), name='thread_list'),
    path('forums/<slug:forum_slug>/threads/<slug:thread_slug>/posts/', PostListView.as_view(), name='post_list'),
    path('forums/<slug:forum_slug>/threads/<slug:thread_slug>/posts/<slug:slug>/', PostDetailView.as_view(),
         name='post_detail'),
    path('profile', profile_view, name='profile'),
    path('register', RegisterView.as_view(), name='register'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('create-post', CreatePostView.as_view(), name='create-post'),
    path('logout/', views.logout, name='logout'),
    path('get_threads_for_forum/<int:forum_id>/', GetThreadsForForumView.as_view(), name='get_threads_for_forum'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

forum_app/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.utils import timezone
import datetime
from django.contrib.auth.models import User


# Create your models here.


class Forum(models.Model):
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def __str__(self):
        return self.title


class Thread(models.Model):
    title = models.CharField(max_length=200)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    started_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.TextField(max_length=200)
    content = models.TextField()
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def __str__(self):
        return f"Post by {self.created_by.username} in {self.thread.title}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, default='avatars/avatar13.jpg')
    signature = models.CharField(max_length=200, blank=True)
    post_count = models.PositiveIntegerField(default=0)

    def increment_post_count(self):
        self.post_count += 1
        self.save()

    def __str__(self):
        return self.user.username if self.user else ""


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Comment by {self.created_by.username} on {self.post.slug}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=Post)
def increment_post_count(sender, instance, created, **kwargs):
    if created:
        profile = UserProfile.objects.get(user=instance.created_by)
        profile.increment_post_count()


def generate_slug(instance, source_field):
    return slugify(getattr(instance, source_field))


@receiver(pre_save, sender=Forum)
def create_slug(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = generate_slug(instance, 'title')


@receiver(pre_save, sender=Thread)
def create_thread_slug(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = generate_slug(instance, 'title')


@receiver(pre_save, sender=Post)
def create_post_slug(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = generate_slug(instance, 'title')[:50]

forum_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import Textarea

from .models import Comment, Post, Forum, Thread

from forum_app.models import UserProfile


class RegisterForm(UserCreationForm):  # регистрационная форма
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)


class CommentForm(forms.ModelForm):  # форма для написания комментария
    class Meta:
        model = Comment
        fields = ['content', ]
        labels = {
            'content': '',  # Пустая строка для уборки надписи
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

        # Добавляем параметр no-resize для отключения изменения размера
        self.fields['content'].widget = Textarea(attrs={'rows': 10, 'cols': 35, 'style': 'resize: none;'})


class AvatarUploadForm(forms.Form):  # форма для загрузки аватара в странице профиля
    avatar = forms.ImageField()


class CreatePostForm(forms.ModelForm):
    forum = forms.ModelChoiceField(queryset=Forum.objects.all(), empty_label=None)
    thread = forms.ModelChoiceField(queryset=Thread.objects.all(), empty_label=None)

    class Meta:
        model = Post
        fields = ['forum', 'thread', 'title', 'content']

forum_app/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, FormMixin, DeleteView
from .forms import RegisterForm, CommentForm, AvatarUploadForm, CreatePostForm
from .models import Forum, Thread, Post, UserProfile, Comment
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.utils.text import slugify
import uuid
from django.shortcuts import redirect
from django.urls import reverse


# Create your views here.

# Отображение контента
class ForumListView(ListView):
    model = Forum
    template_name = 'forum_app/forum.html'  # Подменяем имя шаблона, если по умолчанию не подходит
    context_object_name = 'forums'


class ThreadListView(ListView):
    model = Thread
    template_name = 'forum_app/thread.html'
    context_object_name = 'threads'

    def get_queryset(self):
        self.forum = get_object_or_404(Forum, slug=self.kwargs['forum_slug'])
        return Thread.objects.filter(forum=self.forum)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['forum'] = self.forum
        return context


class PostListView(ListView):
    model = Post
    template_name = 'forum_app/posts.html'
    context_object_name = 'posts'

    def get_queryset(self):
        self.thread = get_object_or_404(Thread, slug=self.kwargs['thread_slug'])
        return Post.objects.filter(thread=self.thread)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['thread'] = self.thread
        return context


class PostDetailView(DetailView):
    model = Post
    slug_field = 'slug'
    template_name = 'forum_app/post.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['comments'] = Comment.objects.filter(post=self.object)
        return context

    def post(self, request, *args, **kwargs):
        post = self.get_object()  # Получаем текущий объект Post

        # Обработка отправки комментария
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post  # Используем post вместо self.object
            comment.created_by = request.user
            comment.save()

            # Перенаправление на ту же страницу с постом после добавления комментария
            return redirect(reverse('forum_app:post_detail', kwargs={'forum_slug': post.thread.forum.slug,
                                                                     'thread_slug': post.thread.slug,
                                                                     'slug': post.slug}))

        context = self.get_context_data()
        context['comment_form'] = comment_form
        return self.render_to_response(context)


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        # Эта функция будет вызвана, чтобы проверить, имеет ли пользователь право на удаление комментария
        comment = self.get_object()
        return self.request.user == comment.created_by

    def get_success_url(self):
        # Возвращаем URL, куда перейти после успешного удаления комментария
        comment = self.get_object()
        return reverse('forum_app:post_detail', kwargs={
            'forum_slug': comment.post.thread.forum.slug,
            'thread_slug': comment.post.thread.slug,
            'slug': comment.post.slug
        })


# Регистрация
class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy("profile")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def signature(request):
    user_profile = UserProfile.objects.get(user=request.user)
    context = {
        'user_profile': user_profile
    }

    return render(request, 'forum_app/profile.html', context)


def profile_view(request):
    if request.user.is_authenticated:
        user_profile = UserProfile.objects.get(user=request.user)

        if request.method == 'POST':
            form = AvatarUploadForm(request.POST, request.FILES)
            if form.is_valid():
                user_profile.avatar = form.cleaned_data['avatar']
                user_profile.save()
                return redirect('/profile')  # Перенаправление на страницу профиля после загрузки
        else:
            form = AvatarUploadForm()

        return render(request, 'forum_app/profile.html', {'form': form, 'user_profile': user_profile})
    else:
        return redirect('login')


class CreatePostView(FormView):
    form_class = CreatePostForm
    template_name = 'forum_app/creation-post.html'

    def form_valid(self, form):
        new_post = form.save(commit=False)
        unique_slug = f"{slugify(new_post.title)}-{str(uuid.uuid4())[:8]}"
        new_post.slug = unique_slug
        new_post.created_by = self.request.user
        new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('forum_app:create-post')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['threads'] = Thread.objects.all()
        return context


class GetThreadsForForumView(View):
    def get(self, request, forum_id):
        threads = Thread.objects.filter(forum_id=forum_id).values('id', 'title')
        return JsonResponse(list(threads), safe=False)

forum_app/templates/forum_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'forum_app/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% block extra_head %} {% endblock %}
</head>
<body>
<header>
    <nav>
        <ul>
            <a href="http://127.0.0.1:8000/forums">Главная</a>
            <a href="#">О сайте</a>
            <a href="#">Контакты</a>
            <a href="http://127.0.0.1:8000/profile">Профиль</a>
            <a href="http://127.0.0.1:8000/create-post">Создать пост</a>
        </ul>
    </nav>
</header>

<main>
    {% block content %} {% endblock %}
</main>

<footer>
    <p>&copy; 2023, Artem Chernenko</p>
</footer>

{% block extra_body %}{% endblock %}
</body>
</html>

forum_app/templates/forum_app/comment_confirm_delete.html
{% extends "forum_app/base.html" %}

{% block content %}
  <h2>Вы уверены, что хотите удалить этот комментарий?</h2>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Удалить">
  </form>
{% endblock %}

forum_app/templates/forum_app/creation-post.html
{% extends "forum_app/base.html" %}
{% load static %}

{% block content %}

<div class="form-container">
    <form method="post" class="post-form" id="postForm">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.forum.id_for_label }}" class="form-label">Форум:</label>
            {{ form.forum }}
        </div>
        <div class="form-group">
            <label for="{{ form.thread.id_for_label }}" class="form-label">Тред:</label>
            <select id="id_thread" name="thread" class="form-select select-thread">
                <option value="" selected="selected">---------</option>
            </select>
        </div>
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}" class="form-label">Заголовок:</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="{{ form.content.id_for_label }}" class="form-label">Текст поста:</label>
            {{ form.content }}
        </div>
        <button type="submit" class="btn btn-primary form-submit-button">Создать пост</button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const forumSelect = document.getElementById('id_forum');
        const threadSelect = document.getElementById('id_thread');

        if (forumSelect && threadSelect) {
            setTimeout(() => {
                forumSelect.dispatchEvent(new Event('change'));
            }, 100); // Добавляем небольшую задержку перед вызовом события change

            forumSelect.addEventListener('change', function() {
                const forumId = this.value;
                threadSelect.innerHTML = '<option value="">---------</option>';  // Очищаем текущие варианты тем

                // Если выбран форум, отправляем AJAX запрос для получения тем этого форума
                if (forumId) {
                    fetch(`/get_threads_for_forum/${forumId}`)
                        .then(response => response.json())
                        .then(data => {
                            data.forEach(thread => {
                                const option = document.createElement('option');
                                option.value = thread.id;
                                option.textContent = thread.title;
                                threadSelect.appendChild(option);
                            });
                        })
                        .catch(error => console.error("Error fetching data:", error));
                }
            });
        }
    });
</script>
{% endblock %}

forum_app/templates/forum_app/forum.html
{% extends "forum_app/base.html" %}

{% block content %}
    <h1>Список форумов:</h1>
<div class="listcontent">
<ul>
    {% for forum in forums %}
        <li>
            <h2><a href="{{ forum.slug }}/threads/">{{ forum.title }}</a></h2>
            <p>{{ forum.description }}</p>
        </li>
    {% empty %}
        <li>На данный момент нет форумов.</li>
    {% endfor %}
    </ul>
</div>
    {% block extra_body %}{% endblock %}
{% endblock %}

forum_app/templates/forum_app/post.html
{% extends "forum_app/base.html" %}

{% block content %}
<h1>Пост:</h1>
<div class="listcontent">

        <ul>
        <li>
            <h2>{{ post.title }}</a>
                <h4>{{ post.content }}</h4>
                <p>By {{ post.created_by }}</p></h2>
        </li>
    </ul>

{% for comment in comments %}
  <div class="comments">
    <p>{{ comment.content }}</p>
    <p>By {{ comment.created_by.username }}</p>
      {% if user.is_authenticated and user.username == comment.created_by.username %}
        <a href="{% url 'forum_app:comment_delete' comment.pk %}">Удалить</a>
      {% endif %}
  </div>

{% endfor %}

<!-- Comment form -->
<div class="comment_form my-custom-style">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ comment_form.content.label_tag }}
            {{ comment_form.content }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>
</div>
{% block extra_body %}{% endblock %}
{% endblock %}

forum_app/templates/forum_app/posts.html
{% extends "forum_app/base.html" %}

{% block content %}
<h1>Посты:</h1>

<div class="listcontent">
    <ul>
        {% for post in posts %}
        <li>
            <h2><a href="{{ post.slug }}/">{{ post.title }}</a>

                <p>{{ post.content }}</p>
                <p>By {{ post.created_by }}</p></h2>
        </li>

        {% empty %}
        <li>На данный момент нет постов.</li>
        {% endfor %}
    </ul>
    {% block extra_body %}{% endblock %}
    {% endblock %}

forum_app/templates/forum_app/profile.html
{% extends "forum_app/base.html" %}
{% load static %}

{% block content %}
<div class="account-container">
    <div class="profile_image">
        <img src="{{ user_profile.avatar.url }}" alt="User avatar">
    </div>

    <div class="change-avatar">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="{{ form.avatar.id_for_label }}">Выберите файл аватара:</label>
            {{ form.avatar }}
            <button type="submit">Установить</button>
        </form>
    </div>
    <div class="account_info">
        <h4 class="account_name">{{ user.username }}</h4>
        <span>Подпись: {{ user_profile.signature }}</span>
    </div>
    <div class="account_btns">
        <button class="Change_password_btn"
                onclick="location.href='{% url 'password_change' %}'">Поменять пароль
        </button>
        <form method="post" action="{% url 'logout' %}?next=/profile">
            {% csrf_token %}
            <button class="Logout_btn"
                    onclick="location.href='{% url 'logout' %}?next=/profile'">Выйти
            </button>
        </form>
    </div>
</div>
{% endblock %}

forum_app/templates/forum_app/thread.html
{% extends "forum_app/base.html" %}

{% block content %}
    <h1>Список тредов:</h1>
<div class="listcontent">
    <ul>
    {% for thread in threads %}
        <li>
            <h2><a href="{{ thread.slug }}/posts/">{{ thread.title }}</a></h2>

            <p>{{ thread.forum }}</p>
        </li>

    {% empty %}
        <li>На данный момент нет тредов.</li>
    {% endfor %}
    </ul>
    </div>
    {% block extra_body %}{% endblock %}
{% endblock %}

<h2><a href="{% url 'post_list' forum_slug=forum.slug thread_slug=thread.slug %}">{{ thread.title }}</a></h2>
            <h2><a href="threads/{{ thread.slug }}/">{{ thread.title }}</a></h2>